// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    KoFi: typeof import('./src/components/ko-fi.vue')['default']
    Patreon: typeof import('./src/components/patreon.vue')['default']
    VideoEntry: typeof import('./src/components/video-entry.vue')['default']
  }
}

export {}
