/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IMdiAlert: typeof import('~icons/mdi/alert')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiLock: typeof import('~icons/mdi/lock')['default']
    IMdiPlayCircle: typeof import('~icons/mdi/play-circle')['default']
    IMdiPlusBoxMultiple: typeof import('~icons/mdi/plus-box-multiple')['default']
    MediaList: typeof import('./src/components/MediaList.vue')['default']
    VideoEntry: typeof import('./src/components/video-entry.vue')['default']
    VPatreon: typeof import('./src/components/v-patreon.vue')['default']
  }
}
